Repository debatecore/debate-tools, pull requests merged in 2024-05, with the labels that each got.

#40 Update German translations
  src/data/strings.json
Labels: enhancement

#44 Add CONTRIBUTING.md
  doc/CONTRIBUTING.md
Labels: documentation

#41 Filter motions
  README.md
  src/components/Checkbox.tsx
  src/components/GenericButton.tsx
  src/components/MotionDisplay.tsx
  src/components/MotionGenerator.tsx
  src/components/MotionsFilter.tsx
  src/components/icons/Filter.tsx
  src/data/motion.json
  src/data/strings.json
  src/types/language.ts
  src/types/motion.ts
Labels: enhancement

#47 [42] fix awful windows countryflag unicode display
  package-lock.json
  package.json
  src/components/FlagIcon.tsx
  src/components/GenericSelect.tsx
  src/components/LangSwitch.tsx
  src/data/strings.json
Labels: bug

#51 [50] license the project
  LICENSE
  README.md
  src/app/page.tsx
  src/data/strings.json
Labels: documentation

#52 [34] display motions with non breakable spaces (and other motion fixes)
  src/data/motion.json
  src/types/motion.ts
Labels: bug

#53 [48] swap increment and decrement buttons in debate conf
  src/components/TimeInput.tsx
Labels: bug

#49 [25] Add bell sound packs (ZTM Transit bell / more)
  LEGAL.md
  README.md
  public/KBING!.mp3
  public/KONCTR.mp3
  public/KZADAN.mp3
  src/app/oxford-debate/page.tsx
  src/app/oxford-debate/setup/page.tsx
  src/app/sound-demonstration/page.tsx
  src/components/Clock.tsx
  src/components/icons/Trophy.tsx
  src/data/strings.json
  src/types/debate.ts
  src/types/soundPack.ts
Labels: enhancement

#57 [56] fix ztm bell paths
  src/types/soundPack.ts
Labels: bug

#55 [54] add code formatter config
  .prettierrc
Labels: enhancement
