Repository debatecore/debate-tools, pull requests merged in 2024-06, with the labels that each got.

#62 [61] resolve motiongenerator cssconflicts
  src/components/MotionGenerator.tsx
Labels: miscellaneous

#60 [59] adjust volume of ztm pack sounds
  public/KBING!.mp3
  src/app/oxford-debate/page.tsx
  src/app/sound-demonstration/page.tsx
  src/components/Clock.tsx
  src/components/SoundPlayer.tsx
  src/types/soundPack.ts
Labels: bug, miscellaneous

#58 [35] submit custom logos
  package-lock.json
  public/display-images/MOW2018.png
  public/display-images/MOW2024.png
  src/app/oxford-debate/page.tsx
  src/app/oxford-debate/setup/page.tsx
  src/components/Clock.tsx
  src/components/ClockDisplayImage.tsx
  src/data/strings.json
  src/lib/imageToBase64.ts
  src/types/debate.ts
  tsconfig.json
Labels: enhancement

#72 [68, 70] fix MOW logos not loading & add PND branding logo option
  public/display-images/PND2024.png
  src/components/ClockDisplayImage.tsx
  src/types/debate.ts
Labels: bug, enhancement, miscellaneous

#66 [65] add PLD 2024 final motions
  src/data/motion.json
Labels: motion

#80 [69] rename "Oxford Debate Conduction" to "Oxford Debate Clock"
  src/app/page.tsx
  src/data/strings.json
Labels: locales

#76 [67] Fix custom image base64 conversion
  package-lock.json
  src/components/ClockDisplayImage.tsx
  src/lib/imageToBase64.ts
Labels: bug

#83 [82] change the default speech time to 5 minutes
  src/types/debate.ts
Labels: miscellaneous

#86 [85] Update README.md with a PND entry
  README.md
Labels: documentation
