Repository debatecore/debate-tools, pull requests merged in 2024-07, with the labels that each got.

#91 [79] Set up Playwright
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  tests/main-menu.test.ts
Labels: enhancement

#93 [87] fix clock images
  src/app/oxford-debate/setup/page.tsx
  src/components/ClockDisplayImage.tsx
  src/components/GenericSelect.tsx
  src/components/LangSwitch.tsx
  tests/clockimage.test.ts
Labels: bug

#77 [36] translate "minutes" and "seconds" in time inputs
  .github/workflows/jest.yml
  .github/workflows/playwright.yml
  jest.config.ts
  package-lock.json
  package.json
  playwright.config.ts
  src/components/TimeInput.tsx
  src/data/strings.json
  src/lib/useLocalizedGrammaticalNumber.ts
  tests/e2e/clockimage.test.ts
  tests/e2e/main-menu.test.ts
  tests/unit-tests/useLocalizedGrammaticalNumber.test.ts
Labels: miscellaneous, locales

#89 [84] add zsk logo option
  public/display-images/ZSK.webp
  src/components/ClockDisplayImage.tsx
  src/types/debate.ts
Labels: enhancement

#95 94 mention use of debate tools in zsk school endeavours in readme
  README.md
Labels: documentation
