Repository debatecore/debate-tools, pull requests merged in 2024-08, with the labels that each got.

#102 [96] validate motion.json
  src/data/motion.json
  tests/unit-tests/motions.test.ts
  tests/unit-tests/motionsValidationHelperFunctions.test.ts
Labels: enhancement, motion

#101 [90] add visual feedback to finished debates
  src/app/oxford-debate/page.tsx
  src/components/Clock.tsx
  src/data/strings.json
  tailwind.config.ts
Labels: enhancement, parity

#104 [64] add a main menu button to the motion generator
  src/components/MotionGenerator.tsx
Labels: bug

#106 [105] fix the "about" footer link
  src/components/DebatecoreFooter.tsx
  tests/e2e/footer-links.test.ts
Labels: bug

#103 [98] "Copy motion" button
  package-lock.json
  package.json
  src/components/MotionDisplay.tsx
  src/components/MotionGenerator.tsx
  src/components/icons/Copy.tsx
  src/data/strings.json
Labels: enhancement
